version: '3'

services:
  web:
    restart: on-failure
    build: ./web
    expose:
      - "8000"
    depends_on:
      - db
      - rabbit
    volumes:
      - ./web:/web
      - web-django:/usr/src/app
    env_file: &envfile 
      - .env
    environment:
      SECRET_KEY: ${WEB_KEY}
      DB_PASS: ${DB_PASSWORD}
      DEBUG: 'false'
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && /usr/local/bin/gunicorn mysite.wsgi:application -w 2 -b :8000"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/cert:/etc/ssl
      - ./web/static:/www/static
    links:
      - web:web
      - flower:flower

  db:
    image: mariadb
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mdbdata:/var/lib/mysql
    restart: on-failure
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


  rabbit:
    image: rabbitmq:latest
    env_file: *envfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmqdata:/home/user
    
  worker:
    restart: on-failure
    build: ./web
    env_file: *envfile
    volumes:
      - ./web:/app
    depends_on:
      - rabbit
      - db
    command: ["celery",
              "-A",
              "mysite",
              "worker",
              "--loglevel=INFO"]

  flower:
    image: mher/flower 
    restart: on-failure
    env_file: *envfile
    command: ['flower',
              '--broker=${FLOWER_BROKER}',
              '--address=0.0.0.0',
              '--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}',
              '--port=5555']
    expose:
      - "5555"
    depends_on:
      - rabbit

volumes:
  web-django:
  web-static:
  mdbdata:
  rabbitmqdata:
  celerydata:
